[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'foundry_test'
cache_path  = 'forge-cache'
gas_reports = ["*"]
no_match_contract = 'Echidna'
solc_version= '0.8.17'

evm_version = 'london'

[fuzz]
max_test_rejects=2147483647
runs=200
