name: solhint-ci
on: [pull_request]
jobs:
  solhint:
    name: runner / solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: solhint
        uses: contractshark/inject-solhint-ci@latest
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          solhint_input: 'packages/contracts/contracts/*.sol'
